apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bees-postgres-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 8Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bees-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bees-postgres
  template:
    metadata:
      labels:
        app: bees-postgres
    spec:
      containers:
        - name: bees-postgres
          image: postgres:15
          envFrom:
            - secretRef:
                name: bees-secrets
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bees-postgres-data

---

apiVersion: v1
kind: Service
metadata:
  name: bees-postgres
spec:
  selector:
    app: bees-postgres
  ports:
    - port: 5432
      targetPort: 5432
